// <auto-generated />
using Bizim.pk.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bizim.pk.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310200249_InitialSupabase")]
    partial class InitialSupabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bizim.pk.API.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Badge")
                        .HasColumnType("text");

                    b.Property<string>("BadgeColor")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OnSale")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("Reviews")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SaleDiscount")
                        .HasColumnType("numeric");

                    b.Property<int>("Sales")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Badge = "BEST SELLER",
                            BadgeColor = "orange",
                            Image = "https://aodour.pk/cdn/shop/files/O1CN01cW8Q8j1uX7OoksflV__2670546046-0-cib_2340556f-c04a-421d-bf8d-43c529e6ec9e.jpg?v=1740306031&width=2048",
                            Name = "Premium Leather Handbag",
                            OnSale = true,
                            OriginalPrice = 35000m,
                            Permissions = "Create,Edit,Delete",
                            Price = 25000m,
                            ProductId = "#PRD-001",
                            Quantity = 50,
                            Rating = 4.7999999999999998,
                            Reviews = 124,
                            SaleDiscount = 110m,
                            Sales = 125,
                            Status = true
                        },
                        new
                        {
                            Id = "2",
                            Image = "https://aodour.pk/cdn/shop/files/O1CN01cW8Q8j1uX7OoksflV__2670546046-0-cib_2340556f-c04a-421d-bf8d-43c529e6ec9e.jpg?v=1740306031&width=2048",
                            Name = "Modern Crossbody Bag",
                            OnSale = false,
                            Permissions = "Create,Edit,Delete",
                            Price = 18500m,
                            ProductId = "#PRD-002",
                            Quantity = 0,
                            Rating = 4.5,
                            Reviews = 89,
                            SaleDiscount = 0m,
                            Sales = 0,
                            Status = false
                        },
                        new
                        {
                            Id = "3",
                            Badge = "TRENDING",
                            BadgeColor = "red",
                            Image = "https://aodour.pk/cdn/shop/files/O1CN01cW8Q8j1uX7OoksflV__2670546046-0-cib_2340556f-c04a-421d-bf8d-43c529e6ec9e.jpg?v=1740306031&width=2048",
                            Name = "Classic Tote Bag",
                            OnSale = true,
                            OriginalPrice = 28000m,
                            Permissions = "Create,Edit,Delete",
                            Price = 22000m,
                            ProductId = "#PRD-003",
                            Quantity = 120,
                            Rating = 4.9000000000000004,
                            Reviews = 215,
                            SaleDiscount = 90m,
                            Sales = 89,
                            Status = true
                        },
                        new
                        {
                            Id = "4",
                            Badge = "LIMITED",
                            BadgeColor = "orange",
                            Image = "https://aodour.pk/cdn/shop/files/O1CN01cW8Q8j1uX7OoksflV__2670546046-0-cib_2340556f-c04a-421d-bf8d-43c529e6ec9e.jpg?v=1740306031&width=2048",
                            Name = "Minimalist Backpack",
                            OnSale = true,
                            OriginalPrice = 45000m,
                            Permissions = "Create,Edit,Delete",
                            Price = 32000m,
                            ProductId = "#PRD-004",
                            Quantity = 30,
                            Rating = 4.7000000000000002,
                            Reviews = 156,
                            SaleDiscount = 100m,
                            Sales = 52,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
